### ISSUE TITLE
Run tests

### ISSUE THREAD

**Issue by hadim** [conda-forge/vispy-feedstock#19]
No tests are run because no backend is detected during the build even with pyqt 5 installed.

See https://github.com/conda-forge/vispy-feedstock/pull/18#issuecomment-554440339 for context.

**Comment by djhoese** [comment]
As mentioned in #18, I think running vispy's tests in conda-forge's CIs would be very difficult. It would require installing OpenGL and having a virtual display set up for OpenGL to write to. I'm going to close this as a wontfix.
