### ISSUE TITLE
Headless Testing

### ISSUE THREAD

**Issue by kmuehlbauer** [conda-forge/vispy-feedstock#2]
To do some built-in vispy testing, we can add `pyqt` as dependency in test->requires of `meta.yaml`.

AFAIK we could use `Xvfb` on linux to get headless testing done. But then we would need that in `yum_requirements.yml`. What options do we have for osx and windows in terms of headless testing? 

I found this CFEP here: https://github.com/conda-forge/conda-forge-enhancement-proposals/pull/7, but this seems not quite fitting here, as we need headless X11 only for testing. Is there anything more to know, @ocefpaf?

**Comment by ocefpaf** [comment]
You can hack your `.travis.yml` file in a similar way to `yum_requirements.txt` to add `xquartz like https://github.com/conda-forge/ncl-feedstock/blob/master/.travis.yml#L17

> I found this CFEP here: conda-forge/conda-forge-enhancement-proposals#7

Unfortunately the that CFEP stalled. I'll try to revive it.

**Comment by kmuehlbauer** [comment]
@ocefpaf

> You can hack your .travis.yml file in a similar way to yum_requirements.txt to add `xquartz like https://github.com/conda-forge/ncl-feedstock/blob/master/.travis.yml#L17

Will that not add `xquartz` to the final packages? This should definitely only be loaded in the testing stage here on conda-forge.

**Comment by ocefpaf** [comment]
> Will that not add `xquartz` to the final packages

It will be the same situation we have with Linux, where we expected X11 to be present and it usually is. There are some corner cases where people have headless docker images where that is not true, but I don't think that situation happens with OS X.

**Comment by kmuehlbauer** [comment]
OK, thanks, I'll try when the feedstock has settled (finally gets its osx builds).
