### ISSUE TITLE
Backports for 0.11.0

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/vispy-feedstock#54]
### Comment:

If i am motivated enough, would you accept some backports to 0.11.0 to enable itto work with PySide 6?

**Comment by hmaarrfk** [comment]
seems like 6.5.0 broke much more than vispy 0.11.0

**Comment by djhoese** [comment]
I guess my main question is why 0.11.0 and not one of the newer versions (0.13.0 released on Friday)?

**Comment by hmaarrfk** [comment]
presently released napari is pinned to 0.11.
